### ISSUE TITLE
如何去掉高亮当前列的效果

### ISSUE THREAD

**Issue by lightning-li** [ma6174/vim#107]
![image](https://cloud.githubusercontent.com/assets/7557388/16221810/59ef5818-37c7-11e6-9d01-26a80f3ac655.png)
尝试过去掉文件中的set cuc，不起作用，请问如何去掉文件中的那条高亮当前列的竖线

**Comment by luckxiang** [comment]
去掉所有的set cuc， 然后重新开个终端打开vim试试

**Comment by lightning-li** [comment]
@luckxiang 解决~同时去掉了set cursorcolumn
