### ISSUE TITLE
Error detected while processing function <SNR>109_RunPyflakes:

### ISSUE THREAD

**Issue by GJBLUE** [ma6174/vim#112]
python 2.7.12

Error detected while processing function <SNR>109_RunPyflakes:
line   53:
E927: Invalid action: ''

**Comment by liuguiyangnwpu** [comment]
maybe you can disable this funcion

```
let g:pyflakes_use_quickfix = 0
```

add this line to your .vimrc

**Comment by GJBLUE** [comment]
Thanks!
