### ISSUE TITLE
MAC OS 10.9.4, 启动时报错

### ISSUE THREAD

**Issue by legatoo** [ma6174/vim#43]
错误信息如下：
`Error detected while processing /Users/steven/.vim/plugin/vimim.vim:
line  473:
E128: Function name must start with a capital or "s:": g:vimim_slash()
line  474:
E121: Undefined variable: s:starts
E15: Invalid expression: col(".") - 1 - s:starts.column
line  475:
E121: Undefined variable: s:starts
E116: Invalid arguments for function strpart(getline("."), s:starts.column, range)
E15: Invalid expression: strpart(getline("."), s:starts.column, range)
line  476:
E121: Undefined variable: chinese
E116: Invalid arguments for function substitute(chinese,'\w','','g')
E15: Invalid expression: substitute(chinese,'\w','','g')
line  477:
E121: Undefined variable: word
E116: Invalid arguments for function empty(word) ? @_ : word
E15: Invalid expression: empty(word) ? @_ : word
line  478:
E121: Undefined variable: word
E116: Invalid arguments for function len(word) / s:multibyte
E15: Invalid expression: len(word) / s:multibyte
line  479:
E121: Undefined variable: repeat_times
E116: Invalid arguments for function repeat("\<Left>\<Delete>",repeat_times) . g:vimim_esc()
E15: Invalid expression: repeat("\<Left>\<Delete>",repeat_times) . g:vimim_esc(
line  481:
E193: :endfunction not inside a function
line  483:
E128: Function name must start with a capital or "s:": g:vimim_bracket(offset)
line  485:
E121: Undefined variable: s:starts
E15: Invalid expression: col(".") - 1 - s:starts.column
line  486:
E121: Undefined variable: range
E15: Invalid expression: range / s:multibyte + a:offset
line  487:
E121: Undefined variable: repeat_times
E15: Invalid expression: repeat_times
line  492:
E133: :return not inside a function
line  493:
E193: :endfunction not inside a function
line  606:
E128: Function name must start with a capital or "s:": g:vimim_esc()
line  608:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.windowless || s:mode.onekey
line  618:
E193: :endfunction not inside a function
line  624:
E128: Function name must start with a capital or "s:": g:vimim_cycle_vimim()
line  625:
E121: Undefined variable: s:cjk
E116: Invalid arguments for function len(s:cjk.filename)  " backdoor to cycle all 4 vimim modes
E15: Invalid expression: len(s:cjk.filename)  " backdoor to cycle all 4 vimim modes
line  637:
E133: :return not inside a function
line  638:
E193: :endfunction not inside a function
line  640:
E128: Function name must start with a capital or "s:": g:vimim_label(key)
line  641:
E121: Undefined variable: a:key
E15: Invalid expression: a:key
line  661:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.windowless && key =~ '\d'
line  665:
E193: :endfunction not inside a function
line  667:
E128: Function name must start with a capital or "s:": g:vimim_page(key)
line  668:
E121: Undefined variable: a:key
E15: Invalid expression: a:key
line  688:
E193: :endfunction not inside a function
line  690:
E128: Function name must start with a capital or "s:": g:wubi()
line  691:
E121: Undefined variable: s:gi_dynamic_on
E15: Invalid expression: s:gi_dynamic_on
line  692:
E133: :return not inside a function
line  694:
E121: Undefined variable: s:mode
E15: Invalid expression: pumvisible() || s:mode.windowless && s:omni ? '\<C-E>' : ""
line  695:
E121: Undefined variable: s:wubi
E15: Invalid expression: s:wubi && empty(len(get(split(s:keyboard),0))%4)
line  699:
E193: :endfunction not inside a function
line  701:
E128: Function name must start with a capital or "s:": g:vimim_hjkl(key)
line  702:
E121: Undefined variable: a:key
E15: Invalid expression: a:key
line  719:
E193: :endfunction not inside a function
line  736:
E128: Function name must start with a capital or "s:": g:punctuation(key)
line  737:
E121: Undefined variable: a:key
E15: Invalid expression: a:key
line  738:
E121: Undefined variable: s:toggle_punctuation
E15: Invalid expression: s:toggle_punctuation > 0
line  747:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.windowless && s:gi_dynamic
line  752:
E193: :endfunction not inside a function
line  754:
E128: Function name must start with a capital or "s:": g:vimim_single_quote()
line  758:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.windowless && s:gi_dynamic
line  762:
E133: :return not inside a function
line  769:
E193: :endfunction not inside a function
line  771:
E128: Function name must start with a capital or "s:": g:vimim_double_quote()
line  773:
E121: Undefined variable: s:toggle_punctuation
E15: Invalid expression: s:toggle_punctuation > 0
line  780:
E193: :endfunction not inside a function
line  782:
E128: Function name must start with a capital or "s:": g:vimim_bslash()
line  784:
E121: Undefined variable: s:toggle_punctuation
E15: Invalid expression: s:toggle_punctuation > 0
line  789:
E193: :endfunction not inside a function
line  795:
E128: Function name must start with a capital or "s:": g:vimim_gi()
line  796:
E121: Undefined variable: s:windowless
E15: Invalid expression: s:windowless
line  797:
E117: Unknown function: s:vimim_start
E15: Invalid expression: s:vimim_start()
line  799:
E193: :endfunction not inside a function
line  801:
E128: Function name must start with a capital or "s:": g:vimim_tab(gi)
line  805:
E117: Unknown function: s:vimim_left
E116: Invalid arguments for function len(s:vimim_left()))
E116: Invalid arguments for function empty(len(s:vimim_left()))
E15: Invalid expression: empty(len(s:vimim_left()))
line  814:
E193: :endfunction not inside a function
line  836:
E128: Function name must start with a capital or "s:": g:vimim_pagedown()
line  843:
E193: :endfunction not inside a function
line  845:
E128: Function name must start with a capital or "s:": g:vimim_space()
line  859:
E121: Undefined variable: s:pattern_not_found
E15: Invalid expression: s:pattern_not_found
line  872:
E117: Unknown function: <SNR>40_vimim_reset_after_insert
line  874:
E193: :endfunction not inside a function
line  876:
E128: Function name must start with a capital or "s:": g:vimim_enter()
line  882:
E117: Unknown function: s:vimim_left
E15: Invalid expression: s:vimim_left() || s:mode.windowless
line  890:
E121: Undefined variable: s:smart_enter
E15: Invalid expression: s:smart_enter == 1
line  898:
E193: :endfunction not inside a function
line  900:
E128: Function name must start with a capital or "s:": g:vimim_one_key_correction()
line  903:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.windowless || s:mode.static && pumvisible()
line  914:
E193: :endfunction not inside a function
line  916:
E128: Function name must start with a capital or "s:": g:vimim_backspace()
line  922:
E193: :endfunction not inside a function
line  952:
E128: Function name must start with a capital or "s:": g:vimim_onekey()
line  960:
E121: Undefined variable: s:ctrl6
E116: Invalid arguments for function empty(s:ctrl6)
E15: Invalid expression: empty(s:ctrl6)
line  975:
E193: :endfunction not inside a function
line 1051:
E128: Function name must start with a capital or "s:": g:vimim_chinese()
line 1052:
E121: Undefined variable: g:vimim_mode
E15: Invalid expression: g:vimim_mode =~ 'static' ? s:static : s:dynamic
line 1053:
E121: Undefined variable: s:ui
E116: Invalid arguments for function empty(s:ui.frontends) ? -1 : s:switch ? 0 : 1
E15: Invalid expression: empty(s:ui.frontends) ? -1 : s:switch ? 0 : 1
line 1054:
E133: :return not inside a function
line 1055:
E193: :endfunction not inside a function
line 1143:
E128: Function name must start with a capital or "s:": g:vimim_visual()
line 1177:
E133: :return not inside a function
line 1178:
E193: :endfunction not inside a function
line 2695:
E128: Function name must start with a capital or "s:": g:vimim_search()/
line 2714:
E193: :endfunction not inside a function
line 3125:
E128: Function name must start with a capital or "s:": g:vimim()
line 3127:
E121: Undefined variable: s:pageup_pagedown
E116: Invalid arguments for function empty(s:pageup_pagedown) ? "" : s:keyboard
E15: Invalid expression: empty(s:pageup_pagedown) ? "" : s:keyboard
line 3130:
E193: :endfunction not inside a function
line 3132:
E128: Function name must start with a capital or "s:": g:omni()
line 3134:
E121: Undefined variable: s:mode
E15: Invalid expression: s:mode.static ? '\<C-N>\<C-P>' : '\<C-P>\<Down>'
line 3137:
E193: :endfunction not inside a function`

使用bash建议安装法安装。
回车后可以正常开启vim，插件貌似工作正常。

Sincerely

**Comment by ma6174** [comment]
`vimim.vim` 这个插件我已经在git库里面删除了，你可以尝试删除试试或者下载最新的
