### ISSUE TITLE
Bundle安装时无法安装Command-T

### ISSUE THREAD

**Issue by aqua7regia** [ma6174/vim#52]
在BundleInstall过程中，一直卡在Processing 'git://git.wincent.com/command-t.git'过程中无法继续下去。

**Comment by sherlockzoom** [comment]
我也出现了同样的问题,然后我就跳过它继续安装下一步了

**Comment by aqua7regia** [comment]
这个问题我已经解决了，这次安装不成功，就换个时间再试，一般试个两三次就好了，估计是它的网站被墙了，连接不到。
