### ISSUE TITLE
您好，请问配置了gdb吗？应该怎么使用？

### ISSUE THREAD

**Issue by kingvision** [ma6174/vim#60]
一直想使用gdb。请问你配置了gdb吗？
还有一个问题，显示行的一条长长的线，能关掉吗？使用哪个命令？

谢谢！

**Comment by ma6174** [comment]
gdb调试不同语言调试方式可能不太一致，你可以根据你使用的语言去网上找一下相关配置。

高亮光标所在行的那条线可以通过删除`set cul`来取消。

https://github.com/ma6174/vim/blob/master/.vimrc#L35
