### ISSUE TITLE
自动补全问题

### ISSUE THREAD

**Issue by VonFry** [ma6174/vim#61]
默认是会自动强出自动补全列表。不过这个列表好象有问题点？第一选项是默认选中的，一但tab或ctrl-n之后就直接跳到第二个了。但是我想直接用第一个哦，如果是用c-y，反应特别慢。要等一会。

顺便问一句。这里的自动补全用的是什么插件？

otl小白，不要介意

**Comment by PierreHao** [comment]
OMNI

**Comment by PierreHao** [comment]
omni
